USE master
GO


CREATE DATABASE MailsAndSenders
ON PRIMARY (
NAME = N'MailsAndSenders',
FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\MailsAndSenders.mdf',
SIZE = 8192 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 65536 KB
)
LOG ON (
NAME = N'MailsAndSenders_log',
FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\MailsAndSenders_log.ldf',
SIZE = 8192 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 65536 KB
)
GO

ALTER DATABASE MailsAndSenders
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE OFF,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
COMPATIBILITY_LEVEL = 150,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NESTED_TRIGGERS = ON,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT OFF,
RECOVERY FULL,
RECURSIVE_TRIGGERS OFF,
TRANSFORM_NOISE_WORDS = OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE MailsAndSenders
COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE MailsAndSenders
SET ENABLE_BROKER
GO

ALTER DATABASE MailsAndSenders
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE MailsAndSenders
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER DATABASE MailsAndSenders
SET QUERY_STORE = OFF
GO

USE MailsAndSenders
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER AUTHORIZATION ON DATABASE::MailsAndSenders TO [DESKTOP-96D0KUM\Татьяна]
GO
USE MailsAndSenders
GO

IF DB_NAME() <> N'MailsAndSenders' SET NOEXEC ON
GO

--
-- Create table [dbo].[SmtpServer]
--
PRINT (N'Create table [dbo].[SmtpServer]')
GO
CREATE TABLE dbo.SmtpServer (
  Id int IDENTITY,
  Address nvarchar(255) NOT NULL,
  Port int NOT NULL,
  CONSTRAINT PK_SmtpServer_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Sender]
--
PRINT (N'Create table [dbo].[Sender]')
GO
CREATE TABLE dbo.Sender (
  Id int IDENTITY,
  Name nvarchar(255) NOT NULL,
  Address nvarchar(255) NOT NULL,
  Login nvarchar(255) NOT NULL,
  Password nvarchar(255) NOT NULL,
  CONSTRAINT PK_Sender_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Email]
--
PRINT (N'Create table [dbo].[Email]')
GO
CREATE TABLE dbo.Email (
  Id int IDENTITY,
  Value nvarchar(max) NOT NULL,
  Name nvarchar(max) NOT NULL,
  CONSTRAINT PK_Email_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT MailsAndSenders.dbo.Email ON
GO
INSERT MailsAndSenders.dbo.Email(Id, Value, Name) VALUES (1, N'polyatikina.tatyana@gmail.com', N'Полятыкина Татьяна (gmail.com)')
INSERT MailsAndSenders.dbo.Email(Id, Value, Name) VALUES (2, N'ttn.plt@yandex.ru', N'Полятыкина Татьяна (yandex.ru)')
GO
SET IDENTITY_INSERT MailsAndSenders.dbo.Email OFF
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT MailsAndSenders.dbo.SmtpServer ON
GO
INSERT MailsAndSenders.dbo.SmtpServer(Id, Address, Port) VALUES (1, N'yandex.ru', 587)
INSERT MailsAndSenders.dbo.SmtpServer(Id, Address, Port) VALUES (2, N'gmail.com', 587)
GO
SET IDENTITY_INSERT MailsAndSenders.dbo.SmtpServer OFF
GO

CREATE TABLE [dbo].[Recipient](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](255) NOT NULL, 
 CONSTRAINT [PK_Recipient_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Message](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Subject] [nvarchar](500) NOT NULL,
	[Body] [nvarchar](max) NOT NULL, 
 CONSTRAINT [PK_Message_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO